[2024-11-04 06:19:05,202 ] werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.165.98:5000
[2024-11-04 06:19:05,202 ] werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-11-04 06:19:55,100 ] werkzeug - INFO - 127.0.0.1 - - [04/Nov/2024 06:19:55] "GET / HTTP/1.1" 200 -
[2024-11-04 06:19:55,159 ] werkzeug - INFO - 127.0.0.1 - - [04/Nov/2024 06:19:55] "[33mGET /styles.css HTTP/1.1[0m" 404 -
[2024-11-04 06:19:57,917 ] werkzeug - INFO - 127.0.0.1 - - [04/Nov/2024 06:19:57] "GET / HTTP/1.1" 200 -
[2024-11-04 06:19:57,980 ] werkzeug - INFO - 127.0.0.1 - - [04/Nov/2024 06:19:57] "[33mGET /styles.css HTTP/1.1[0m" 404 -
[2024-11-04 06:23:20,601 ] root - INFO - Entered the load_object method of utils
[2024-11-04 06:23:21,614 ] root - INFO - Exited the load_object method of utils
[2024-11-04 06:23:21,615 ] root - INFO - Entered the load_object method of utils
[2024-11-04 06:23:21,686 ] root - INFO - Exited the load_object method of utils
[2024-11-04 06:23:21,686 ] app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\HP\Documents\Python Projects\Real-Estate-MLOPs-Project\real_estate\pipeline\prediction_pipeline.py", line 23, in predict
    data_scaled = preprocessor.transform(features)
                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'transform'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\envs\realEstate\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\envs\realEstate\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\envs\realEstate\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\anaconda3\envs\realEstate\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Documents\Python Projects\Real-Estate-MLOPs-Project\app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Documents\Python Projects\Real-Estate-MLOPs-Project\real_estate\pipeline\prediction_pipeline.py", line 28, in predict
    raise realEstateException(e, sys)
real_estate.exception.realEstateException: Error occurred python script name [C:\Users\HP\Documents\Python Projects\Real-Estate-MLOPs-Project\real_estate\pipeline\prediction_pipeline.py] line number [23] error message ['numpy.ndarray' object has no attribute 'transform']
[2024-11-04 06:23:21,762 ] werkzeug - INFO - 127.0.0.1 - - [04/Nov/2024 06:23:21] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
